security:
    # @link http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html#securitybundle-integration
    providers:
        in_memory:
            memory:
                users:
                    swagger:
                        password: '%swagger_docs_password%'

    encoders:
        App\Document\User:
            algorithm: bcrypt
            cost: 12
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: /login$
            security: false
            methods: [POST]

        docs:
            pattern: ^/(docs|api)
            http_basic: ~
            logout_on_user_change: true

        api:
            pattern: ^/(users|login)(?!token)
            stateless: true
            guard:
                authenticators:
                    - App\Security\JwtAuthenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        Administrator: Director
        Director: User
