parameters:
    secret: ThisTokenIsNotSoSecretChangeIt

    mongodb_server:           '%env(SY_MONGODB_SERVER)%'
    env(SY_MONGODB_SERVER):   mongodb://mongo:27017
    mongodb_database:         demo

    jwt_private_key_path: '%kernel.root_dir%/var/jwt/private.pem'
    jwt_public_key_path: '%kernel.root_dir%/var/jwt/public.pem'
    jwt_token_ttl: 86400
    jwt_registered_claims:
        - iss
        - sub
        - exp
        - iat
    jwt_custom_claims:
        - roles
        - companyId

    swagger_docs_password: $2y$12$1TVdGigAZ5hM.z5oirk0BeswDH6mj5Joui0I2qsl3DPbF6JHxoNNS
