bendbennett_demo:
    resource: "@BendbennettDemoBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout

# _swagger-ui:
#     resource: '@HBSwaggerUiBundle/Resources/config/routing.yml'
#     prefix: /api
