<?php

namespace Bendbennett\DemoBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration as Config;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * @Config\Route("/api")
 */
class ApiDocumentationController extends Controller
{
    /**
     * @Config\Route("")
     */
    public function indexAction()
    {
        return $this->render('api/index.html.twig');
    }

    /**
     * A model definition in the Swagger json is required in order to render the "Model/Model Schema" within Swagger UI
     * for a specific request so that the body of the request can be populated by clicking on the Model Schema.
     *
     * Because there is no "model" for Login (i.e., email / password) as it's just 2 fields on the User object, rather
     * than annotating a model, the definition can be manually created and added to the "definitions" in the json
     * generated by calling Swagger::scan. Definition can then be referenced from the annotations
     * (e.g., @ SWG\Schema(ref="#/definitions/Login" in LoginController).
     *
     * @Config\Route("/json")
     */
    public function jsonAction()
    {
        $swagger = \Swagger\scan($this->container->getParameter('kernel.root_dir'). '/../src');

        return new JsonResponse($swagger);
    }
}
