monolog:
    handlers:
        main:
            type: stream
            level: debug
            channels: ["!event"]
            handler: nested
        nested:
            type:  stream
            # https://stackoverflow.com/questions/38499825/symfony-logs-to-stdout-inside-docker-container
            path:  "php://stdout"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        deprecation:
            type: stream
            handler: nested
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
