<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/oa")
 */
class ApiDocumentationController
{
    protected $kernelRootDir;

    public function __construct($kernelRootDir)
    {
        $this->kernelRootDir = $kernelRootDir;
    }

    /**
     * A model definition in the Swagger json is required in order to render the "Model/Model Schema" within Swagger UI
     * for a specific request so that the body of the request can be populated by clicking on the Model Schema.
     *
     * Because there is no "model" for Login (i.e., email / password) as it's just 2 fields on the User object, rather
     * than annotating a model, the definition can be manually created and added to the "definitions" in the json
     * generated by calling Swagger::scan. Definition can then be referenced from the annotations
     * (e.g., @ OA\JsonContent(ref="#/components/schemas/Login") in LoginController).
     *
     * @Route("/swagger.json")
     */
    public function jsonAction()
    {
        $swagger = \OpenApi\scan($this->kernelRootDir . '/src');

        return new JsonResponse($swagger);
    }
}
