services:

    # listener
    Bendbennett\DemoBundle\Listener\DoctrineMongoListener:
        autowire: true
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: postLoad }

    Bendbennett\DemoBundle\Listener\ExceptionListener:
        tags:
            -  { name: kernel.event_listener, event: kernel.exception }

    # manager
    Bendbennett\DemoBundle\Manager\UserManager:
        arguments:
            - "@doctrine_mongodb.odm.default_connection"
            - "@doctrine_mongodb.odm.default_configuration"
            - "@doctrine_mongodb.odm.event_manager"
            - "@security.password_encoder"
        public: true

    # security
    Bendbennett\DemoBundle\Security\JwtAuthenticator:
        autowire: true

    Bendbennett\DemoBundle\Security\UserVoter:
        autowire: true
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

    # service
    Bendbennett\DemoBundle\Service\ActiveJwtService:
        autowire: true
        public: true

    Bendbennett\DemoBundle\Service\ActiveJwtServiceInterface: '@Bendbennett\DemoBundle\Service\ActiveJwtService'

    Bendbennett\DemoBundle\Service\AuthenticationService:
        autowire: true
        public: true

    Bendbennett\DemoBundle\Service\JwtService:
        autowire: true
        arguments:
            $tokenTimeToLive: '%jwt_token_ttl%'
            $registeredClaims: '%jwt_registered_claims%'
            $customClaims: '%jwt_custom_claims%'
        public: true

    Bendbennett\DemoBundle\Service\RequestService:
        autowire: true

    Bendbennett\DemoBundle\Service\RequestServiceInterface: '@Bendbennett\DemoBundle\Service\RequestService'

    Bendbennett\DemoBundle\Service\SerializerService:
        autowire: true
        public: true

    Bendbennett\DemoBundle\Service\SerializerServiceInterface: '@Bendbennett\DemoBundle\Service\SerializerService'

    Bendbennett\DemoBundle\Service\ValidatorService:
        autowire: true
        public: true
