services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Bendbennett\DemoBundle\:
        resource: '../../../../../src/Bendbennett/DemoBundle/*'

    # controller
    Bendbennett\DemoBundle\Controller\:
        resource: '../../../../../src/Bendbennett/DemoBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    Bendbennett\DemoBundle\Controller\ApiDocumentationController:
        arguments:
            - '%kernel.project_dir%'
        public: true

    # listener
    Bendbennett\DemoBundle\Listener\DoctrineMongoListener:
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: postLoad }

    Bendbennett\DemoBundle\Listener\ExceptionListener:
        tags:
            -  { name: kernel.event_listener, event: kernel.exception }

    # manager
    Bendbennett\DemoBundle\Manager\UserManager:
        arguments:
            - "@doctrine_mongodb.odm.default_connection"
            - "@doctrine_mongodb.odm.default_configuration"
            - "@doctrine_mongodb.odm.event_manager"
            - "@security.password_encoder"
        public: true

    # security
    Bendbennett\DemoBundle\Security\UserVoter:
        tags:
            - { name: security.voter }

    # service
    Bendbennett\DemoBundle\Service\ActiveJwtService:
        public: true

    Bendbennett\DemoBundle\Service\AuthenticationService:
        public: true

    Bendbennett\DemoBundle\Service\JwtService:
        arguments:
            $tokenTimeToLive: '%jwt_token_ttl%'
            $registeredClaims: '%jwt_registered_claims%'
            $customClaims: '%jwt_custom_claims%'
        public: true

    Bendbennett\DemoBundle\Service\SerializerService:
        public: true

    Bendbennett\DemoBundle\Service\ValidatorService:
        public: true
